

services:
  plex-recommendation: 
    image: williamcook/plex-recommendation:latest
    build: 
      context: ./backend
      dockerfile: ./build/docker/Dockerfile
    restart: always 
    ports:
      - "8090:8090"
    depends_on: 
      weaviate:
        condition: service_healthy
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
    - "8080:8080"
    - "50051:50051"
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "wget", "-nv", "--spider", "http://weaviate:8080/v1/.well-known/ready"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 15s

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ${PWD}/pg-data/:/var/lib/postgresql/data/
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:14269"]
    environment:
      - LOG_LEVEL=info
      - COLLECTOR_OTLP_ENABLED=true
